language: r
sudo: true
warnings_are_errors: false
cache: packages

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgdal1-dev libproj-dev

r_packages:
  - devtools
  - rgdal

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never
  slack: huckley:XufS5mf1g1GF3MjqPMVVcyAB

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings --as-cran --run-donttest"
    - _R_CHECK_TIMINGS_="0"
